# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

        config.vm.define "server" do |server|
        config.vm.boot_timeout = 600
        server.vm.box = 'centos/7'

        server.vm.host_name = 'server'
        server.vm.network :private_network, ip: "10.0.0.100"

        server.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end

         server.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
         SHELL

         server.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbook-selinux.yml"
            ansible.become = "true"
         end

    end
end