---
# tasks file for dhcp
- name: epel-release
  yum: 
    name: epel-release 
    state: installed

- name: Set SELinux in permissive mode 
  command: setenforce 0

- name: Install dhcp-server
  yum: 
    name: dhcp-server
    state: present
  notify: Restart dhcp

- name: DHCP conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: Restart dhcp

- name: Enable dhcp
  systemd:
    name: dhcpd
    state: restarted
    enabled: yes

