---
prometheus_version: 2.30.3
prometheus_binary_local_dir: ''

prometheus_config_dir: /etc/prometheus
prometheus_db_dir: /var/lib/prometheus

prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_web_external_url: ''

prometheus_storage_retention: "30d"
prometheus_storage_retention_size: "0"


prometheus_global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# Alternative config file name, searched in ansible templates path.
prometheus_config_file: 'prometheus.yml.j2'