---
- name: restart prometheus
  become: true
  systemd:
    daemon_reload: true
    name: prometheus
    state: restarted

- name: restart blackbox exporter
  become: true
  systemd:
    daemon_reload: true
    name: blackbox_exporter
    state: restarted

- name: reload blackbox exporter
  become: true
  systemd:
    name: blackbox_exporter
    state: reloaded    

- name: restart alertmanager
  become: true
  systemd:
    daemon_reload: true
    name: alertmanager
    state: restarted

- name: reload alertmanager
  become: true
  systemd:
    name: alertmanager
    state: reloaded    