# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

   config.vm.provision "shell", path: "pam_script.sh"

   config.vm.define "server" do |server|
      server.vm.box = 'centos/7'

      server.vm.boot_timeout = 600

      server.vm.host_name = 'server'
      server.vm.network :private_network, ip: "192.168.10.10"

      server.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
      end

      server.vm.provision "shell", inline: <<-SHELL

      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh

      SHELL

   end

end