---
- name: Create WordPress Document Root
  file:
    path: "{{ wordpress_install_directory }}"
    state: directory
    owner: "apache"
    group: "apache"
    mode: '0755'

- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "{{ wordpress_install_directory }}"
    remote_src: yes
    creates: "{{ wordpress_directory }}"

- name: Setting ownership
  file:
    path: "{{ wordpress_directory }}"
    owner: apache
    group: apache
    state: directory
    recurse: true
    mode: '0775'

- name: Copy sample config file
  command: mv {{ wordpress_directory }}/wp-config-sample.php {{ wordpress_directory }}/wp-config.php creates={{ wordpress_directory }}/wp-config.php
  become: yes
 
- name: Update WordPress config file
  template:
    src: "wp-config.php.j2"
    dest: "{{ wordpress_directory }}/wp-config.php"
  notify: Restart httpd 