
MACHINES = {
	:inetRouter1 => {
			:box_name => "centos/7",
			:net => [
					   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net1"},
					]
	  },
	  :inetRouter2 => {
		:box_name => "centos/7",
		:net => [
				   {ip: '192.168.255.5', adapter: 2, netmask: "255.255.255.252", gateway: "192.168.255.1", virtualbox__intnet: "router-net2"},
				]
  	  },	  
	  :centralRouter => {
			:box_name => "centos/7",
			:net => [
					   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", gateway: "192.168.255.1", virtualbox__intnet: "router-net1"},
					   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.224", virtualbox__intnet: "dir-net"},
					   {ip: '192.168.255.6', adapter: 4, netmask: "255.255.255.252", virtualbox__intnet: "router-net2"},
					]
	  },
	  :centralServer => {
			:box_name => "centos/7",
			:net => [
					   {ip: '192.168.0.10', adapter: 2, netmask: "255.255.255.224", gateway: "192.168.0.1", virtualbox__intnet: "dir-net"}
					]
	  }
	}

Vagrant.configure("2") do |config|

	MACHINES.each do |boxname, boxconfig|
		config.vm.define boxname do |box|
	
			box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxname.to_s
			box.vm.boot_timeout = 600
	
			boxconfig[:net].each do |ipconf|
			  box.vm.network "private_network", ipconf
			end
	
			if boxconfig.key?(:public)
			  box.vm.network "public_network", boxconfig[:public]
			end

			if boxname.to_s == "inetRouter2"
				box.vm.network "forwarded_port", guest: 8080, guest_ip: "192.168.255.5", host: 9999, host_ip: "127.0.0.1",  protocol: "tcp"
			  end
			
	
			box.vm.provision "shell", inline: <<-SHELL
			  mkdir -p ~root/.ssh
					cp ~vagrant/.ssh/auth* ~root/.ssh
			  
			SHELL
	
			box.vm.provision "ansible" do |ansible|
			 ansible.become = true
			 ansible.playbook = "network.yml"
		   end 
	
		  end
	
	  end
	
end
