- name: 'Install nginx'
  yum:
    name: nginx
    state: present    

- name: 'Disable default router for eth0'
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^DEFROUTE='
    line: DEFROUTE="no"
  notify: restart network

- name: 'Add default route for eth1'
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    regexp: '^GATEWAY='
    line: GATEWAY=192.168.0.1
  notify: restart network

- name: 'Start and enable nginx'
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Restart network
  service:
    name: network
    state: restarted