- name: Addressing and routing
  command: "{{ item }}"
  with_items:
    - iptables -t nat -A PREROUTING -p tcp -m tcp --dport 8080 -j DNAT --to-destination 192.168.0.10:80
    - iptables -t nat -A OUTPUT -p tcp --dport 8080 -j DNAT --to-destination 192.168.0.10:80
    - iptables -t nat -A POSTROUTING -j MASQUERADE

- name: Add route
  lineinfile:
    dest: /etc/sysconfig/network-scripts/route-eth1
    line: "192.168.0.0/16 via 192.168.255.6 dev eth1"
    create: yes
    owner: root

- name: Restart network
  service:
    name: network
    state: restarted