
- name: addressing and routing
  command: "{{ item }}"
  with_items:
    - iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
    - iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    - iptables -A INPUT -s 192.168.255.2 -p tcp --dport 22 -j REJECT

- name: Add route
  lineinfile:
    dest: /etc/sysconfig/network-scripts/route-eth1
    line: "192.168.0.0/16 via 192.168.255.2 dev eth1"
    create: yes
    owner: root

- name: 'Configure sshd'
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'
  notify: restart sshd

- name: 'Install knock server'
  yum:
    name: 'http://li.nux.ro/download/nux/dextop/el7/x86_64/knock-server-0.7-2.el7.nux.x86_64.rpm'
    state: present

- name: 'Start and enable knock server'
  systemd:
    name: knockd
    state: started
    enabled: yes

- name: 'Configure knock.conf server'
  copy:
    src: knockd.conf
    dest: /etc/
  notify: restart knockd    

- name: 'Configure knock server'
  lineinfile:
    dest: /etc/sysconfig/knockd
    line: OPTIONS="-i eth1"
  notify: restart knockd    

- name: Create user
  user: name=knock

- name: Set password to user
  shell: echo knock:12345 | sudo chpasswd
  no_log: True

- name: Restart network
  service:
    name: network
    state: restarted

- name: restart sshd
  systemd:
    name: sshd
    state: restarted