Vagrant.configure("2") do |config|

  config.vm.define "pxeserver" do |server|
    config.vm.box = 'centos/8.4'
    config.vm.box_url = 'http://cloud.centos.org/centos/8/vagrant/x86_64/images/CentOS-8-Vagrant-8.4.2105-20210603.0.x86_64.vagrant-virtualbox.box'

    config.vm.boot_timeout = 600
  
    server.vm.host_name = 'pxeserver'
    server.vm.network :private_network, 
                       ip: "10.0.0.20", 
                       virtualbox__intnet: 'pxenet'
  
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  
    server.vm.provision "ansible", playbook: "playbook.yml"
    end


    config.vm.define "pxeclient" do |pxeclient|
      pxeclient.vm.box = 'centos/8.4'
      pxeclient.vm.host_name = 'pxeclient'
      pxeclient.vm.network :private_network, ip: "10.0.0.21"
      pxeclient.vm.provider :virtualbox do |vb|
        vb.memory = "2048"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize [
            'modifyvm', :id,
            '--nic1', 'intnet',
            '--intnet1', 'pxenet',
            '--nic2', 'nat',
            '--boot1', 'net',
            '--boot2', 'none',
            '--boot3', 'none',
            '--boot4', 'none'
          ]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
    end

    config.vm.define "testserver" do |testserver|
      config.vm.box = 'centos/8.4'
      config.vm.box_url = 'http://cloud.centos.org/centos/8/vagrant/x86_64/images/CentOS-8-Vagrant-8.4.2105-20210603.0.x86_64.vagrant-virtualbox.box'
  
      config.vm.boot_timeout = 600
    
       testserver.vm.host_name = 'testserver'
      testserver.vm.network :private_network, 
                         ip: "10.0.0.10", 
                         virtualbox__intnet: 'pxenet'
    
      testserver.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
    end


  
  end