---
# - name: Add host to /etc/hosts
#   lineinfile:
#     path: /etc/hosts
#     line: "{{ item }}"
#   loop:
#     - '{{ proxy_server_ip }} proxy.myproject.com'
#     - '{{ web_server_ip }} web.myproject.com'    
#     - '{{ master_server_ip }} master.myproject.com'    
#     - '{{ replica_server_ip }} replica.myproject.com'
#     - '{{ nfs_server_ip }} nfs.myproject.com'
#     - '{{ monitoring_server_ip }} monitoring.myproject.com'        

- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Update all installed packages using YUM module
  yum:
    name: '*'
    state: latest
    update_cache: yes
    update_only: yes    

- name: Install packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bind-utils
      - wget
      - net-tools
      - mc
      - policycoreutils-python
      - setools
      - setroubleshoot-server

- name: Set sysctl params
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.conf
    ignoreerrors: yes
    reload: yes
  with_dict: "{{ sysctl_params }}"

- name: firewalld start & enable
  service:
    name: firewalld
    state: started
    enabled: yes

# Enable SELinux
- selinux:
    policy: targeted
    state: enforcing    