---
- name: Install packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - policycoreutils-python
      - setools
      - setroubleshoot-server

- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present
  notify: Restart nginx

- name: Enable nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: HTML
  template:
    src: page.html.j2
    dest: /usr/share/nginx/html/index.html

- name: Nginx conf
  template:
    src: nginx.default.conf.j2
    dest: /etc/nginx/nginx.conf
##    notify: Reload nginx