---
- name: Restart httpd
  systemd:
    name: httpd
    state: restarted
    enabled: yes

- name: Reload httpd
  systemd:
    name: httpd
    state: reloaded

- name: Restart nfs-server
  systemd:
    name: nfs-server
    state: restarted
    enabled: yes    
