# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :'webserver' => {
        :box_name => "centos/7",
        :ip => '10.0.0.100',
        :mem => '1024',
        :cpu => '1'
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip]
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", boxconfig[:mem]]
          end

          box.vm.provision "ansible" do |ansible|
            ansible.become = true
            ansible.verbose = "v"
            ansible.playbook = "provision/dweb_playbook.yml"
          end
      end
  end
end
