---
# tasks file
- name: Creates directory pxelinux
  file:
    path: /var/lib/tftpboot/pxelinux
    state: directory

- name: Copy tftpboot files
  shell: cp -a /tftpboot/. /var/lib/tftpboot/pxelinux

- name: Creates directory pxelinux.cfg
  file:
    path: /var/lib/tftpboot/pxelinux/pxelinux.cfg
    state: directory

- name: Make PXE menu
  template:
    src: default.j2
    dest: /var/lib/tftpboot/pxelinux/pxelinux.cfg/default

- name: Creates directory for images Centos
  file:
    path: /var/lib/tftpboot/pxelinux/images/CentOS/
    state: directory

- name: Download initrd.img
  shell: curl -O http://ftp.mgts.by/pub/CentOS/7/os/x86_64/images/pxeboot/initrd.img

- name: Download vmlinuz
  shell: curl -O http://ftp.mgts.by/pub/CentOS/7/os/x86_64/images/pxeboot/vmlinuz

- name: Copy files vmlinuz,initrd.img
  shell: cp {vmlinuz,initrd.img} /var/lib/tftpboot/pxelinux/images/CentOS/

- name: Download CentOS
  shell: curl -O http://ftp.mgts.by/pub/CentOS/7/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso

- name: Creates directory /mnt/centos-install
  file:
    path: /mnt/centos-install
    state: directory

- name: mount CentOS.iso
  shell: mount -t iso9660 CentOS-7-x86_64-Minimal-2009.iso /mnt/centos-install        
      
- name: Creates directory centos-autoinstall
  file:
    path: /mnt/centos-autoinstall
    state: directory

- name: Copy ks.cfg
  copy:
    src: '../files/ks.cfg'
    dest: '/mnt/ks.cfg'
   