---
- name: Open Firewall for services
  block:
    - name: Allow Ports
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop: [ '9200/tcp','9300/tcp']

# - name: Allow ports in SELinux
#   seport:
#     ports: "{{ item }}"
#     proto: tcp
#     setype: http_port_t
#     state: present   
#   loop: [ 9200/tcp, 9300/tcp ]    

- name: Install elasticsearch
  yum: 
    name: elasticsearch
    state: latest 
    update_cache: yes

# - name: Create elasticsearch config
#   template:
#     src: elasticsearch.config.j2
#     dest: /etc/elasticsearch/elasticsearch.yml

- name: Ensure extra time for Elasticsearch to start on reboots
  lineinfile:
    path: /usr/lib/systemd/system/elasticsearch.service
    regexp: '^TimeoutStartSec='
    line: "TimeoutStartSec={{ elasticsearch_start_timeout }}"
  become: yes
  tags: configure

- name: Force systemd to reread configs
  systemd: daemon_reload=yes

- name: Enable elasticsearch.service
  systemd:
    name: elasticsearch.service
    enabled: yes

- name: Start elasticsearch.service
  systemd: 
    name: elasticsearch.service
    state: restarted  