---
- name: Open Firewall for services
  block:
    - name: Allow Ports
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop: [ '9115/tcp' ]

- name: Firewalld reload
  shell: firewall-cmd --reload

- name: Create blackbox_exporter system group
  group:
    name: blackbox-exp
    system: true
    state: present

- name: Create blackbox_exporter system user
  user:
    name: blackbox-exp
    system: true
    shell: "/usr/sbin/nologin"
    group: blackbox-exp
    createhome: false

- name: Download blackbox exporter binary to local folder
  become: false
  unarchive:
    src: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp"
    remote_src: true
    creates: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/blackbox_exporter"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: Propagate blackbox exporter binary
  copy:
    src: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/blackbox_exporter"
    dest: "/usr/local/bin/blackbox_exporter"
    mode: 0750
    owner: blackbox-exp
    group: blackbox-exp
  notify:
    - restart blackbox exporter

- name: Create systemd service unit
  template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart blackbox exporter

- name: Configure blackbox exporter
  template:
    src: blackbox_exporter.yml.j2
    dest: /etc/blackbox_exporter.yml
    owner: blackbox-exp
    group: blackbox-exp
    mode: 0644
  notify:
    - reload blackbox exporter

- name: Ensure blackbox_exporter service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: blackbox_exporter
    state: started
    enabled: true        